export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
export const UPDATING_PROFILE = 'UPDATING_PROFILE';
export const UPDATING_PROFILE_IMAGE = 'UPDATING_PROFILE_IMAGE';
